### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by sjkeerthi** [cloudsploit/scans#23]
I tried to install this using npm install 

npm install
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/aws-sdk
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/aws-sdk
npm http GET https://registry.npmjs.org/sax/1.1.5
npm http GET https://registry.npmjs.org/xmlbuilder/2.6.2
npm http GET https://registry.npmjs.org/xml2js/0.4.15
npm http 304 https://registry.npmjs.org/sax/1.1.5
npm http 304 https://registry.npmjs.org/xml2js/0.4.15
npm http 304 https://registry.npmjs.org/xmlbuilder/2.6.2
npm http GET https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/lodash
async@0.9.2 node_modules/async

aws-sdk@2.2.42 node_modules/aws-sdk
├── xml2js@0.4.15
├── sax@1.1.5
└── xmlbuilder@2.6.2 (lodash@3.5.0)

node index.js 

module.js:340
    throw err;
          ^
Error: Cannot find module '/home/aaaaa/scans/../../cloudsploit-secure/scan-test-credentials.json'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/keerthi/scans/index.js:10:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

**Comment by matthewdfuller** [comment]
You can fix this by commenting out the credentials file import line:

`var AWSConfig = require(__dirname...`

Or, you can set it to a file containing your credentials. They have to be configured somewhere for the scans to run.

Pushing a commit shortly to remove this line as a default.
