### ISSUE TITLE
async function auth(token): SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by vijayraje23** [cloudsploit/scans#230]
I have configured azure service principal in index.js file. when running node index.js file getting below error. Please help on this.

[root@localhost scans-master]# pwd
/opt/scans-master
[root@localhost scans-master]# node index.js
/opt/scans-master/node_modules/@octokit/auth-token/dist-node/index.js:5
async function auth(token) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/scans-master/node_modules/@octokit/rest/plugins/authentication/index.js:3:29)
[root@localhost scans-master]#

**Comment by zhujian0805** [comment]
Probably your nodejs version is too low, Please upgrade it to latest and try again.
